### PR TITLE
[Runner] Push `/opt/${target}/${target}/lib{,64}` to linker search path

### LINKED ISSUE #163: `CompilerSupportLibraries_jll` v0.5.0 from GCC 11 breaks some platforms
```console
% julia -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("i686", "linux"))'
sandbox:${WORKSPACE} # mkdir -p ${prefix}
sandbox:${WORKSPACE} # wget -qO - 'https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.0%2B0/CompilerSupportLibraries.v0.5.0.i686-linux-gnu-libgfortran3.tar.gz' | tar xzf - -C ${prefix}
sandbox:${WORKSPACE} # echo 'int main() { return 0; }' | g++ -x c++ - -Wl,--trace -o sanitycheckcpp.exe -L${libdir}
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/bin/ld: mode elf_i386
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/crt1.o
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/crti.o
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/crtbegin.o
/tmp/ccnJKpAc.o
-lstdc++ (/workspace/destdir/lib/libstdc++.so)
-lm (/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/libm.so)
-lgcc_s (/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/lib/libgcc_s.so)
/lib/libc.so.6 (/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/lib/libc.so.6)
(/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/libc_nonshared.a)elf-init.oS
/lib/ld-linux.so.2 (/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/lib/ld-linux.so.2)
-lgcc_s (/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/lib/libgcc_s.so)
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/crtend.o
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/crtn.o
/workspace/destdir/lib/libstdc++.so: undefined reference to `__divmoddi4@GCC_7.0.0'
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/bin/ld: link errors found, deleting executable `sanitycheckcpp.exe'
collect2: error: ld returned 1 exit status
sandbox:${WORKSPACE} # echo 'int main() { return 0; }' | g++ -x c++ - -Wl,--trace -o sanitycheckcpp.exe
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/bin/ld: mode elf_i386
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/crt1.o
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/crti.o
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/crtbegin.o
/tmp/ccMjMAnj.o
-lstdc++ (/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/lib/libstdc++.so)
-lm (/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/libm.so)
-lgcc_s (/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/lib/libgcc_s.so)
/lib/libc.so.6 (/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/lib/libc.so.6)
(/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/libc_nonshared.a)elf-init.oS
/lib/ld-linux.so.2 (/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/lib/ld-linux.so.2)
-lgcc_s (/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/../../../../i686-linux-gnu/lib/libgcc_s.so)
/opt/i686-linux-gnu/bin/../lib/gcc/i686-linux-gnu/4.8.5/crtend.o
/opt/i686-linux-gnu/bin/../i686-linux-gnu/sys-root/usr/lib/crtn.o
sandbox:${WORKSPACE} # ./sanitycheckcpp.exe 
sandbox:${WORKSPACE} # nm ${libdir}/libstdc++.so | grep divmoddi4
         U __divmoddi4@GCC_7.0.0
```
So, when using `CompilerSupportLibraries_jll` v0.5.0 from GCC 11 and `${libdir}` is in the linker search path of libraries `g++` can't compile the simple program because `${libdir}/libstdc++.so` has an undefined symbol `__divmoddi4@GCC_7.0.0`.  We don't have any issues if `${libdir}` isn't in the linker search path and `/opt/${target}/${target}/lib/libstdc++.so` is picked up

### PR DESCRIPTION
**Pull request by giordano**
When compiling with GCC this makes sure its libraries have precedence over
anything else, in particular other compiler libraries that may be elsewhere, for
example `CompilerSupportLibraries_jll` used as dependency during the build.

Fix #163.

Note: I ran the tests of BinaryBuilder on this branch in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1032, seems all good.

### CODE REVIEW

File: test/runners.jl [hunk 1]
```diff
@@ -128,6 +128,41 @@ end
...
+                    std::cout << "Hello World!" << std::endl;
+                    return 0;
+                }
+                """
+                test_script = """
+                set -e
+                # Install `CompilerSupportLibraries_jll` v0.5.0 in the `\${prefix}` to make
+                # sure it doesn't break compilation of the program
+                mkdir -p \${prefix}
+                wget -qO - "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.0%2B0/CompilerSupportLibraries.v0.5.0.\${target}-libgfortran3.tar.gz" | tar xzf - -C \${prefix}
```
Comment (giordano) [inline test/runners.jl:147]: I'm a bit in a rush now and I wanted to get this PR out for testing, but this needs to use the automatic mechanism to install dependencies, instead of manually doing this non-cache-friendly download inside the build.

**Comment by staticfloat** [comment]
Excellent quality as usual, Mosè.

**Comment by giordano** [comment]
Uhm, I suspect this can be a bit problematic when we want to link against libz, libxml2, or libiconv, because these libraries are also here :disappointed: 
```console
sandbox:${WORKSPACE}/srcdir # ls /opt/${target}/${target}/lib64
libatomic.a                 libcilkrts.spec             libgomp.a                   libitm.a                    libobjc.so.4.0.0            libstdc++.so.6.0.23         libz.so.1
libatomic.so                libgcc_s.so                 libgomp.so                  libitm.so                   libquadmath.a               libstdc++.so.6.0.23-gdb.py  libz.so.1.2.11
libatomic.so.1              libgcc_s.so.1               libgomp.so.1                libitm.so.1                 libquadmath.so              libstdc++fs.a
libatomic.so.1.2.0          libgfortran.a               libgomp.so.1.0.0            libitm.so.1.0.0             libquadmath.so.0            libsupc++.a
libcilkrts.a                libgfortran.so              libgomp.spec                libitm.spec                 libquadmath.so.0.0.0        libxml2.so
libcilkrts.so               libgfortran.so.4            libiconv.so                 libobjc.a                   libstdc++.a                 libxml2.so.2
libcilkrts.so.5             libgfortran.so.4.0.0        libiconv.so.2               libobjc.so                  libstdc++.so                libxml2.so.2.9.12
libcilkrts.so.5.0.0         libgfortran.spec            libiconv.so.2.6.1           libobjc.so.4                libstdc++.so.6              libz.so
```
