### PR TITLE
Fix JSON serialization for Dependency with build_version

### LINKED ISSUE #45: `Dependency("package_jll", v"1.2.3")` results in inconsistent compat bounds
https://github.com/JuliaPackaging/Yggdrasil/pull/1718 Used the new syntax `Dependency("GMP_jll", v"6.1.2")`, which however results in inconsistent compat bounds between `Project.toml` and the registry:

* `Project.toml` has a strict dependency on `v6.1.2:` https://github.com/JuliaBinaryWrappers/Singular_jll.jl/blob/85929b66afd6fdd6b877ec60fe8de9fe12661b27/Project.toml#L18
* the registry has a lower bound compat on `v6.1.2`: https://github.com/JuliaRegistries/General/pull/22388/files#diff-190a13cffbbf470e5e0c7f62902925bcR2

The registry here is what we want and the only thing that actually matters, but it's probably better to make these two bounds consistent

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #45

### CODE REVIEW

**Comment by giordano** [comment]
Can you add tests please? :slightly_smiling_face:

**Comment by fingolfin** [comment]
@giordano tests added

File: test/dependencies.jl [hunk 1]
```diff
@@ -33,9 +40,16 @@ end
         jdep = JSON.lower(dep)
         @test jdep == Dict("type" => "dependency", "name" => name, "uuid" => nothing, "version-major" => 0x0, "version-minor" => 0x0, "version-patch" => 0x0)
         @test dependencify(jdep) == dep
+
+        jdep_buildver = JSON.lower(dep_buildver)
+        @test jdep_buildver == Dict("type" => "dependency", "name" => name, "uuid" => nothing, "version-major" => 0x0, "version-minor" => 0x0, "version-patch" => 0x0)
+        # the build_version is currently not serialized, so the following test fails
+        @test_broken dependencify(jdep_buildver) == dep_buildver
```
Comment (giordano) [inline test/dependencies.jl:47]: Should we make this work instead?

Comment (fingolfin) [reply test/dependencies.jl:47]: I am not sure (which is why I left it as-is). I can't think of a usecase for it right now, though, and my feeling was that code I don't write also is code that won't contain bugs ;-) But perhaps @staticfloat can think of a reasons why we might want to serialize the build version?

Comment (giordano) [reply test/dependencies.jl:47]: Ok, I don't think this is super-important now, I'm going to merge

Comment (staticfloat) [reply test/dependencies.jl:47]: Hmmm, it could be important in case we ever want to e.g. know precisely which version of a JLL was pushed up.  We should probably just change whatever preprocessing we're doing to `VersionNumbers` before serializing them to include the build number.
